export const ActionTypes = {
    LOAD_START: "LOAD_START",
    LOAD_SUCCESS: "LOAD_SUCCESS",
    LOAD_ERROR: "LOAD_ERROR",

    UPLOAD_TITLE_CHANGE_START: "UPLOAD_TITLE_CHANGE_START",
    UPLOAD_TITLE_CHANGE_SUCCESS: "UPLOAD_TITLE_CHANGE_SUCCESS",
    UPLOAD_TITLE_CHANGE_ERRORS: "UPLOAD_TITLE_CHANGE_ERRORS",
  };